#ifndef OSIAN_odi_types_h
#define OSIAN_odi_types_h

/* DO NOT EDIT: THIS FILE AUTOMATICALLY GENERATED BY genodi.py */

enum ODI_Environment_types_e {
  /** This value must not be used by any hardware instance. It can be used
   * as a wildcard to specify a device for which the identifier is
   * temporarily unavailable. */
  ODI_ENV_Unknown = 0,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. */
  ODI_ENV_UnregisteredA = 1,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. In combination with UnregisteredA, this
   * allows two in-development devices in the same category to be
   * distinguished. */
  ODI_ENV_UnregisteredB = 2,
  /** Unannounced People Power Company device */
  ODI_ENV_PPCEv3 = 3,
};
enum ODI_Communications_types_e {
  /** This value must not be used by any hardware instance. It can be used
   * as a wildcard to specify a device for which the identifier is
   * temporarily unavailable. */
  ODI_COMM_Unknown = 0,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. */
  ODI_COMM_UnregisteredA = 1,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. In combination with UnregisteredA, this
   * allows two in-development devices in the same category to be
   * distinguished. */
  ODI_COMM_UnregisteredB = 2,
  /** A People Power Company SuRF (Sensor ultra Radio Frequency) developer
   * board. */
  ODI_COMM_SuRF = 3,
  /** Unannounced People Power Company device */
  ODI_COMM_PPCC4 = 4,
};
enum ODI_Energy_types_e {
  /** This value must not be used by any hardware instance. It can be used
   * as a wildcard to specify a device for which the identifier is
   * temporarily unavailable. */
  ODI_ENRG_Unknown = 0,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. */
  ODI_ENRG_UnregisteredA = 1,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. In combination with UnregisteredA, this
   * allows two in-development devices in the same category to be
   * distinguished. */
  ODI_ENRG_UnregisteredB = 2,
  /** Unannounced People Power Company device */
  ODI_ENRG_PPCE3 = 3,
  /** Unannounced People Power Company device */
  ODI_ENRG_PPCE4 = 4,
};
enum ODI_HealthAndSafety_types_e {
  /** This value must not be used by any hardware instance. It can be used
   * as a wildcard to specify a device for which the identifier is
   * temporarily unavailable. */
  ODI_HnS_Unknown = 0,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. */
  ODI_HnS_UnregisteredA = 1,
  /** A value that can be used during development, prior to obtaining an
   * assigned device type from OCG. In combination with UnregisteredA, this
   * allows two in-development devices in the same category to be
   * distinguished. */
  ODI_HnS_UnregisteredB = 2,
};

#endif /* OSIAN_odi_types_h */

