#ifndef _PLATFORM_RED_LED_H_
#define _PLATFORM_RED_LED_H_

#define PLATFORM_LED_COUNT 3

#define PLATFORM_LED_RED 0
#define PLATFORM_LED_GREEN 1
#define PLATFORM_LED_BLUE 2

#endif // _PLATFORM_RED_LED_H_
